### ISSUE TITLE
convert vcf to genotype matrix

### ISSUE THREAD

**Issue by Arlettt** [Mtusti05/qtl-analysis#1]

**Comment by mgalland** [comment]
What I'd like is to fully understand how the VCF file is converted to a genotype file, ready for importation into Rqtl.
Then, if possible, I'd like to automatically generate all the necessary files for a R/qtl2 analysis. 


From the R/qtl2 google group discussion, I obtained this advice from Karl Broman:
> vcf files are generally a big tab-delimited file with some annotation information at the top.
I'll read it into R using data.table::fread() and then pull apart the map information from the genotypes.
You then need founder genotypes, which is maybe part of that data, in order to convert the nucleotide-based SNP calls to AA/AB/BB type genotypes. I use functions from the qtl2convert package: find_consensus_geno() and encode_geno().
Then write back to a CSV file with qtl2convert::write2csv().
karl
